language: python
python:
  - "3.6"
before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libudev-dev
before_install:
  - mv travis_secrets.yaml secrets.yaml
install:
  - pip3 install homeassistant==0.106.5
script:
  - hass -c . --script check_config
notifications:
  email:
    recipients:
      - henrik@tillander.org
    on_success: always
    on_failure: always
  slack: tillander:PgAJbA3KWS8NxGY26AdH7Y97
    

