homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone 
  # URLs 
  external_url: !secret base_url
  internal_url: !secret internal_url
  #Customize names 
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs: 
    - !secret ha_snapshot 
    - !secret ha_video
    - !secret ha_data  
  auth_providers:
    - type: legacy_api_password
      api_password: !secret api_password
    - type: trusted_networks
      trusted_networks:
        - 192.168.100.0/24
        - 127.0.0.1
    - type: homeassistant

# Enable Mobile app 
mobile_app:

# Enable Helpers
input_button:
input_boolean:
input_text:
input_datetime:
counter:
timer:

# Enable Energy
energy:

# Enable streaming 
stream: 


# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  themes: !include_dir_named themes

recorder: 
  purge_keep_days: 14
  db_url: !secret db_url
  exclude: 
    domains: 
      - automation
      - updater
      - group
      - history_graph
      - media_player
    entities:
      - sensor.date
      - sensor.time
      - sensor.date_time

# Enables configuration UI
config:

http:
#  api_password: !secret api_password
#  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate 
  ssl_key: !secret ssl_key 
#  trusted_networks: 
#    - 192.168.100.0/24
#    - 127.0.0.1


logger: 
  default: warning
#  logs: 
#    pydeconz: debug
#    homeassistant.components.deconz: debug

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude: 
    domains: 
      - automation 
      - updater
      - zwave 
      - group
    entities: 
      - sensor.last_boot
      - sensor.date

# View all events in a logbook
logbook:
  exclude: 
    domains: 
      - group 
      - zwave
      - sensor

# Track the sun
sun:

# remote:
#   - platform: harmony
#     name: harmony 
#     host: 192.168.100.136 
#     activity: Watch Movies


# Weather prediction
# sensor:
#  - platform: yr
#    name: Weather
#    forecast: 24
#    monitored_conditions:
#      - temperature
#      - symbol
#      - precipitation
#      - windSpeed
#      - pressure
#      - windDirection
#      - humidity
#      - fog
#      - cloudiness


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml

# automation: !include_dir_list automation

automation: !include automations.yaml
# automation old:  !include_dir_merge_list automation

scene: !include scenes.yaml
scene old: !include_dir_merge_list scene

sensor: !include sensors.yaml

# Controls
input_select: !include input-selects.yaml
input_number: !include input-numbers.yaml

google_assistant:
  project_id: homeassistant-20171104 
#  client_id: !secret ga_client_id 
#  access_token: !secret ga_access_token
  exposed_domains:
    - switch
    - light
    - vacuum

# Zwave configuration
zwave: 
  usb_path: /dev/ttyACM0
  polling_interval: 60000
  autoheal: false

netatmo:
  client_id: !secret netatmo_api
  client_secret: !secret netatmo_secret
#  username: !secret netatmo_username 
#  password: !secret netatmo_password


# Track wifi users through unifi
device_tracker:
#  - platform: unifi
#    host: !secret unifi_host 
#    username: !secret unifi_username 
#    password: !secret unifi_password 
#    verify_ssl: false
#    track_new_devices: no 
#    consider_home: 180
#    interval_seconds: 10

  - platform: ping 
    hosts: 
      firewall: 192.168.100.1
      switch: 192.168.100.253
      ap: 192.168.100.250

notify:
  - name: slack 
    platform: slack 
    api_key: !secret slack_api_key
    default_channel: 'homeassistant'

#light: 
# - platform: lifx


system_health:

spotify: 
  client_id: !secret spotify_id
  client_secret: !secret spotify_secret

home_connect:
  client_id: !secret hc_id
  client_secret: !secret hc_secret 

qvr_pro: 
  host: !secret qvr_host 
  username: !secret qvr_username 
  password: !secret qvr_password 

