homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude 
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 11
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret time_zone 
  #Customize names 
  customize: !include customize.yaml
  packages: !include_dir_named packages
  whitelist_external_dirs: 
    - !secret ha_snapshot 
    - !secret ha_video

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:
  javascript_version: latest
  themes: !include_dir_named themes

recorder: 
  purge_interval: 1
  purge_keep_days: 14
  db_url: !secret db_url
  exclude: 
    domains: 
      - automation
      - updater
      - group
      - history_graph
      - media_player
    entities:
      - sensor.date
      - sensor.time
      - sensor.date__time

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate 
  ssl_key: !secret ssl_key 
  trusted_networks: 
    - 192.168.100.0/24
    - 127.0.0.1

logger: 
  default: warning
#  logs: 
#    pydeconz: debug
#    homeassistant.components.deconz: debug

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  exclude: 
    domains: 
      - automation 
      - updater
      - zwave 
      - group
    entities: 
      - sensor.last_boot
      - sensor.date

# View all events in a logbook
logbook:
  exclude: 
    domains: 
      - group 
      - zwave
      - sensor

# Track the sun
sun:

remote:
  - platform: harmony
    name: harmony 
    host: 192.168.100.136 
    activity: Watch Movies


# Weather prediction
sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
#  - platform: brottsplatskartan

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include_dir_list automation
scene: !include_dir_list scene

# Controls
input_select: !include input-selects.yaml
input_number: !include input-numbers.yaml

google_assistant:
  project_id: homeassistant-20171104 
#  client_id: !secret ga_client_id 
#  access_token: !secret ga_access_token
  exposed_domains:
    - switch
    - light
    - climate

# Zwave configuration
zwave: 
  usb_path: /dev/ttyACM0
  polling_interval: 60000
  autoheal: false

media_player: 
  - platform: plex


netatmo:
  api_key: !secret netatmo_api
  secret_key: !secret netatmo_secret
  username: !secret netatmo_username 
  password: !secret netatmo_password


# Track wifi users through unifi
device_tracker:
  - platform: unifi
    host: !secret unifi_host 
    username: !secret unifi_username 
    password: !secret unifi_password 
    verify_ssl: false
    track_new_devices: no 
    consider_home: 180
    interval_seconds: 10
  
  - platform: ping 
    hosts: 
      firewall: 192.168.100.1
      switch: 192.168.100.253
      ap: 192.168.100.250
     

notify:
  - name: pushbullet 
    platform: pushbullet
    api_key: !secret pb_access_token 
  - name: slack 
    platform: slack 
    api_key: !secret slack_api_key
    default_channel: 'homeassistant'

# tradfri: 
#   host: !secret tradfri_host
#   allow_tradfri_groups: false

#light: 
# - platform: lifx


vacuum:
  - platform: xiaomi_miio
    host: 192.168.100.151
    token: !secret xiaomi_token 
    name: "stadis" 

