alias: "Media player playing"
trigger:
  - platform: state
    entity_id: media_player.living_room
    from: 'off'
condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
action:
    service: scene.turn_on
    entity_id: scene.livingroom_movie
