alias: 'Notify that Henrik is home' 
trigger: 
  platform: state 
  entity_id: device_tracker.cc9f7a9f9afb
  from: 'not_home'
  to: 'home'
action:
  service: notify.pushbullet
  data:
    message: 'Henrik is home'
