alias: 'Notify that Maria is home' 
trigger: 
  platform: state 
  entity_id: device_tracker.galaxy_s7__maria 
  from: 'not_home'
  to: 'home'
action:
  service: notify.pushbullet
  data:
    message: 'Maria is home'
