alias: "Bad weather - lights on!"
trigger: 
  platform: sun 
  event: sunset
  offset: -02:00:00 
condition: 
  condition: and
  conditions: 
    - condition: numeric_state
      entity_id: sensor.weather_cloudiness 
      above: "80" 
    - condition: time
      before: '20:00:00'
action: 
  service: scene.turn_on
  entity_id:
  - scene.br_normal
  - scene.lr_normal
  - scene.er_normal
  - scene.vr_normal
  - scene.or_normal

 
