alias: 'Turn on bathroom light when movement during night'
trigger: 
  platform: state
  entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor_2 
  from: 'off'
  to: 'on'
condition:
  condition: time
  after: '23:00:00'
  before: '07:00:00' 
action:
  service: switch.turn_on
  entity_id:
    - switch.qubino_zmnhbdx_flush_2_relays_switch_2


