alias: "Turn off LIFX when lights turned off in bedroom."
trigger: 
  platform: state
  entity_id: light.marias_light
  from: "on" 
  to: "off"
action:
  service: light.turn_off
  entity_id:
  - light.bedroom_led_strip_
  
 
