alias: "Weekend - Turn off Living room lights in the evening"
trigger: 
  platform: time
  at: "01:00:00"
condition:
  condition: time
  weekday: 
    - sat 
    - sun 
action:
  service: scene.turn_on
  entity_id:
  - scene.lr_off


 
