alias: 'Turn on Hallway light when movement'
trigger: 
  platform: state
  entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor 
  from: 'off'
  to: 'on'
condition:
  condition: time
  after: '07:00:00'
  before: '10:00:00' 
action:
  service: switch.turn_on
  entity_id:
    - switch.switch_3
