alias: "Turn off LIFX when lights turned off in living room."
trigger: 
  platform: state
  entity_id: light.ikea_ps_uplight
  from: "on" 
  to: "off"
action:
  - service: light.turn_off
    entity_id:
    - light.lifx_led_strip
    - light.level_6
    - light.level_16
  - service: switch.turn_off
    entity_id:
    - switch.tellduslivingroom_switch
