alias: "Turn on Living Room lights in the morning at first movement" 
trigger: 
  platform: state
  entity_id: binary_sensor.neo_coolcam_battery_powered_pir_sensor_sensor 
  from: 'off'
  to: 'on'
condition:
  condition: time
  after: '06:00:00'
  before: '07:15:00' 
action: 
  service: scene.turn_on
  entity_id:
  - scene.lr_normal
 
