alias: "Turn off Google Homein Living Room in the morning on weekdays" 
trigger: 
  platform: time
  at: "08:00:00"
condition:
  condition: time
  weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  - service: media_player.turn_off
    data: 
      entity_id: media_player.kitchen_home
