alias: "Turn off Google Homein Living Room in the morning on weekends" 
trigger: 
  platform: time
  at: "10:30:00"
condition:
  condition: time
  weekday:
    - sat
    - sun 
action:
  - service: media_player.turn_off
    data: 
      entity_id: media_player.kitchen_home
