alias: "Turn on P1 on Google home in Living Room in the morning on weekdays" 
trigger: 
  platform: time
  at: "07:00:00"
condition:
  condition: and 
  conditions:
    - condition: time 
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: group.parents 
      state: 'home'
action:
  - service: media_player.volume_set
    data: 
      entity_id: media_player.kitchen_home
      volume_level: 0.3
  - service: media_player.play_media
    data: 
      entity_id: media_player.kitchen_home
      media_content_id: http://sverigesradio.se/topsy/direkt/132-hi-mp3.mp3 
      media_content_type: audio/mp3
