alias: "22:00 and Workstation Turned Off" 
trigger: 
  platform: time 
  at: '22:00:00' 
condition:
  condition: state 
  entity_id: device_tracker.workstation_cartman 
  state: 'not_home'  
action:
  service: switch.turn_off
  entity_id:
  - switch.telldusoffice_switch 


