alias: "Workstation Turned Off and after 2200" 
trigger: 
  platform: state 
  entity_id: device_tracker.workstation_cartman
  from: 'home'
  to: 'not_home'
condition:
  condition: time
  after: '22:00:00' 
action:
  service: switch.turn_off
  entity_id:
  - switch.office_table_light 
