alias: "Turn off lights in Kids' room, Living Room and Bedrom after sunrise"
trigger:
  platform: sun
  event: sunrise
  offset: +01:30:00
condition:
  condition: time
  after: '07:30:00'
action:
  service: scene.turn_on
  entity_id:
  - scene.br_off
  - scene.lr_off
  - scene.er_off
  - scene.vr_off
  - scene.or_off

 
 
