alias: "Turn on lights at sunset in Kids' room, Living Room and Bedroom"
trigger: 
  platform: sun
  event: sunset 
  offset: -01:30:00
condition: 
  condition: time
  before: '20:00:00'
action:
  service: scene.turn_on
  entity_id:
  - scene.br_normal
  - scene.lr_normal
  - scene.er_normal
  - scene.vr_normal
  - scene.or_normal
 
 
