alias: "Turn on P1 on Google home in Living Room in the morning on weekends" 
trigger: 
  platform: time
  at: "08:45:00"
condition:
  condition: and 
  conditions:
    - condition: time 
      weekday:
      - sat 
      - sun
    - condition: state
      entity_id: group.parents 
      state: 'home'
action:
  - service: media_player.volume_set
    data: 
      entity_id: media_player.kitchen_display
      volume_level: 0.3
  - service: media_player.play_media
    data: 
      entity_id: media_player.kitchen_display
      media_content_id: http://sverigesradio.se/topsy/direkt/132-hi-mp3.mp3 
      media_content_type: audio/mp3
