sensor:

  - platform: template
    sensors:
      zwave_pir_hallway:
        friendly_name: 'PIR - Hallway'
        value_template: "{{ states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level |default(-1)|int if states.zwave.neo_coolcam_battery_powered_pir_sensor is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_pir_bathroom:
        friendly_name: 'PIR - Bathroom'
        value_template: "{{ states.zwave.neo_coolcam_battery_powered_pir_sensor_2.attributes.battery_level |default(-1)|int if states.zwave.neo_coolcam_battery_powered_pir_sensor_2 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_pir_shower:
        friendly_name: 'PIR - Shower'
        value_template: "{{ states.zwave.neo_coolcam_battery_powered_pir_sensor_3.attributes.battery_level |default(-1)|int if states.zwave.neo_coolcam_battery_powered_pir_sensor_3 is not none }}"
        unit_of_measurement: '%'
        device_class: battery


  - platform: template
    sensors:
      zwave_door_hallway:
        friendly_name: 'Door Sensor - Hallway'
        value_template: "{{ states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level|default(-1)|int if states.zwave.neo_coolcam_doorwindow_detector is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_fire_alarm:
        friendly_name: 'Fire Alarm - Hallway'
        value_template: "{{ states.zwave.fibaro_system_fgsd002_smoke_sensor.attributes.battery_level|default(-1)|int if states.zwave.fibaro_system_fgsd002_smoke_sensor is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_thermostat_livingroom:
        friendly_name: 'Thermostat - Livingroom'
        value_template: "{{ states.zwave.danfoss_z_thermostat.attributes.battery_level|default(-1)|int if states.zwave.danfoss_z_thermostat is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_thermostat_kitchen:
        friendly_name: 'Thermostat - Kitchen'
        value_template: "{{ states.zwave.danfoss_z_thermostat_2.attributes.battery_level|default(-1)|int if states.zwave.danfoss_z_thermostat_2 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_thermostat_bedroom:
        friendly_name: 'Thermostat - Bedroom'
        value_template: "{{ states.zwave.danfoss_z_thermostat_3.attributes.battery_level|default(-1)|int if states.zwave.danfoss_z_thermostat_3 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_thermostat_elinleft:
        friendly_name: 'Thermostat - Elin Left'
        value_template: "{{ states.zwave.danfoss_z_thermostat_4.attributes.battery_level|default(-1)|int if states.zwave.danfoss_z_thermostat_4 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_thermostat_elinright:
        friendly_name: 'Thermostat - Elin Right'
        value_template: "{{ states.zwave.danfoss_z_thermostat_5.attributes.battery_level|default(-1)|int if states.zwave.danfoss_z_thermostat_5 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_thermostat_vilhelm:
        friendly_name: 'Thermostat - Vilhelm'
        value_template: "{{ states.zwave.danfoss_z_thermostat_6.attributes.battery_level|default(-1)|int if states.zwave.danfoss_z_thermostat_6 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_thermostat_office:
        friendly_name: 'Thermostat - Office'
        value_template: "{{ states.zwave.danfoss_z_thermostat_7.attributes.battery_level|default(-1)|int if states.zwave.danfoss_z_thermostat_7 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_flood_kitchen:
        friendly_name: 'Flood sensor - Kitchen'
        value_template: "{{ states.zwave.aeotec_dsb45_water_sensor.attributes.battery_level|default(-1)|int if states.zwave.aeotec_dsb45_water_sensor is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_flood_bathroom:
        friendly_name: 'Flood sensor - Bathroom'
        value_template: "{{ states.zwave.aeotec_dsb45_water_sensor_2.attributes.battery_level|default(-1)|int if states.zwave.aeotec_dsb45_water_sensor_2 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zwave_door_balcony:
        friendly_name: 'Door Sensor - Balcony door'
        value_template: "{{ states.zwave.telldus_tzdw100_magnet_switch.attributes.battery_level|default(-1)|int if states.zwave.telldus_tzdw100_magnet_switch is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zigbee_temp_freezer:
        friendly_name: 'Temp Sensor - Freezer'
        value_template: "{{ states.sensor.temperature_10.attributes.battery_level|default(-1)|int if states.sensor.temperature_10 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zigbee_temp_refrigerator:
        friendly_name: 'Temp Sensor - Refrigerator'
        value_template: "{{ states.sensor.temperature_7.attributes.battery_level|default(-1)|int if states.sensor.temperature_7 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zigbee_openclose_vilhelm:
        friendly_name: 'Window Sensor - Vilhelm'
        value_template: "{{ states.binary_sensor.openclose_13.attributes.battery_level|default(-1)|int if states.binary_sensor.openclose_13 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zigbee_openclose_office:
        friendly_name: 'Window Sensor - Office'
        value_template: "{{ states.binary_sensor.openclose_14.attributes.battery_level|default(-1)|int if states.binary_sensor.openclose_14 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zigbee_openclose_elin:
        friendly_name: 'Window Sensor - Elin'
        value_template: "{{ states.binary_sensor.openclose_15.attributes.battery_level|default(-1)|int if states.binary_sensor.openclose_15 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

  - platform: template
    sensors:
      zigbee_openclose_kitchen:
        friendly_name: 'Window Sensor - Kitchen'
        value_template: "{{ states.binary_sensor.openclose_16.attributes.battery_level|default(-1)|int if states.binary_sensor.openclose_16 is not none }}"
        unit_of_measurement: '%'
        device_class: battery

group:
  battery_status_view:
    icon: mdi:battery-unknown
    view: yes
    entities:
      - group.device_batteries
      - group.thermostat_batteries
      - group.zigbee_batteries

  device_batteries:
    name: Zwave Batteries
    entities:
      - sensor.zwave_pir_hallway
      - sensor.zwave_pir_bathroom
      - sensor.zwave_pir_shower
      - sensor.zwave_door_hallway
      - sensor.zwave_door_balcony
      - sensor.zwave_fire_alarm
      - sensor.zwave_flood_kitchen
      - sensor.zwave_flood_bathroom

  zigbee_batteries:
    name: ZigBee Batteries
    entities:
      - sensor.bedroom_remote_battery_level
      - sensor.living_room_remote_battery_level
      - sensor.elins_remote_battery_level
      - sensor.vilhelms_remote_battery_level
      - sensor.lumisensor_switchaq3_battery_level
      - sensor.lumisensor_switchaq3_2_battery_level
      - sensor.zigbee_temp_refrigerator
      - sensor.zigbee_temp_freezer
      - sensor.zigbee_openclose_vilhelm
      - sensor.zigbee_openclose_office
      - sensor.zigbee_openclose_elin
      - sensor.zigbee_openclose_kitchen


  thermostat_batteries:
    name: Thermostat Batteries
    entities:
      - sensor.zwave_thermostat_livingroom
      - sensor.zwave_thermostat_kitchen
      - sensor.zwave_thermostat_bedroom
      - sensor.zwave_thermostat_elinleft
      - sensor.zwave_thermostat_elinright
      - sensor.zwave_thermostat_vilhelm
      - sensor.zwave_thermostat_office
  

automation:
  - alias: Low Battery Sensors
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.zwave_pir_hallway
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_pir_bathroom
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_pir_shower
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_door_hallway
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.living_room_remote_battery_level
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.bedroom_remote_battery_level
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.elins_remote_battery_level
        above: 1
        below: 10     
      - platform: numeric_state
        entity_id: sensor.vilhelms_remote_battery_level
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_flood_kitchen
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_flood_bathroom 
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_thermostat_livingroom 
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_thermostat_kitchen 
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_thermostat_bedroom 
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_thermostat_elinleft 
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_thermostat_elinright
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_thermostat_vilhelm
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_thermostat_office 
        above: 1
        below: 10
    action:
      - service: notify.pushbullet
        data_template:
          title: 'Battery low'
          message: >
            '{{ trigger.to_state.name }}'
      - service: notify.slack
        data_template:
          title: 'Battery low'
          message: >
            '{{ trigger.to_state.name }}'
