sensor:
  - platform: template
    sensors:   
      ikea_remote_bedroom:
        friendly_name: 'Ikea Remote - Bedroom'
        value_template: "{{ states.sensor.bedroom.attributes.battery_level|default(-1)|int if states.sensor.bedroom is not none }}"
        unit_of_measurement: '%'
        entity_id: sensor.bedroom
        icon_template: '{% if states.sensor.bedroom.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.sensor.bedroom.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.sensor.bedroom.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.sensor.bedroom.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.sensor.bedroom.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.sensor.bedroom.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.sensor.bedroom.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.sensor.bedroom.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.sensor.bedroom.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.sensor.bedroom.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'

  - platform: template
    sensors:
      ikea_remote_livingroom:
        friendly_name: 'Ikea Remote - Living room'
        value_template: "{{ states.sensor.living_room_remote.attributes.battery_level|default(-1)|int if states.sensor.living_room_remote is not none }}"
        unit_of_measurement: '%'
        entity_id: sensor.living_room_remote
        icon_template: '{% if states.sensor.living_room_remote.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.sensor.living_room_remote.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.sensor.living_room_remote.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.sensor.living_room_remote.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.sensor.living_room_remote.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.sensor.living_room_remote.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.sensor.living_room_remote.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.sensor.living_room_remote.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.sensor.living_room_remote.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.sensor.living_room_remote.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'

  - platform: template
    sensors:
      ikea_remote_elin:
        friendly_name: 'Ikea Remote - Elin'
        value_template: "{{ states.sensor.elins_remote.attributes.battery_level|default(-1)|int if states.sensor.elins_remote is not none }}"
        unit_of_measurement: '%'
        entity_id: sensor.elins_remote
        icon_template: '{% if states.sensor.elins_remote.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.sensor.elins_remote.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.sensor.elins_remote.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.sensor.elins_remote.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.sensor.elins_remote.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.sensor.elins_remote.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.sensor.elins_remote.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.sensor.elins_remote.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.sensor.elins_remote.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.sensor.elins_remote.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'


  - platform: template
    sensors:
      ikea_remote_vilhelm:
        friendly_name: 'Ikea Remote - Vilhelm'
        value_template: "{{ states.sensor.vilhelms_remote.attributes.battery_level|default(-1)|int if states.sensor.vilhelms_remote is not none }}"
        unit_of_measurement: '%'
        entity_id: sensor.vilhelms_remote
        icon_template: '{% if states.sensor.vilhelms_remote.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.sensor.vilhelms_remote.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.sensor.vilhelms_remote.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.sensor.vilhelms_remote.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.sensor.vilhelms_remote.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.sensor.vilhelms_remote.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.sensor.vilhelms_remote.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.sensor.vilhelms_remote.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.sensor.vilhelms_remote.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.sensor.vilhelms_remote.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'


  - platform: template
    sensors:
      zwave_pir_hallway:
        friendly_name: 'PIR - Hallway'
        value_template: "{{ states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level|default(-1)|int if states.zwave.neo_coolcam_battery_powered_pir_sensor is not none }}"
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_battery_powered_pir_sensor 
        icon_template: '{% if states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.zwave.neo_coolcam_battery_powered_pir_sensor.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'


  - platform: template
    sensors:
      zwave_door_hallway:
        friendly_name: 'Door Sensor - Hallway'
        value_template: "{{ states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level|default(-1)|int if states.zwave.neo_coolcam_doorwindow_detector is not none }}"
        unit_of_measurement: '%'
        entity_id: zwave.neo_coolcam_doorwindow_detector
        icon_template: '{% if states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level == 100 %}
                           mdi:battery
                        {% elif states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level >= 90 %}
                           mdi:battery-90
                        {% elif states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level >= 80 %}
                           mdi:battery-80
                        {% elif states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level >= 70 %}
                           mdi:battery-70
                        {% elif states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level >= 60 %}
                           mdi:battery-60
                        {% elif states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level >= 50 %}
                           mdi:battery-50
                        {% elif states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level >= 40 %}
                           mdi:battery-40
                        {% elif states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level >= 30 %}
                           mdi:battery-30
                        {% elif states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level >= 20 %}
                           mdi:battery-20
                        {% elif states.zwave.neo_coolcam_doorwindow_detector.attributes.battery_level >= 10 %}
                           mdi:battery-10
                        {% else %}
                           battery-outline
                        {% endif %}'


group:
  battery_status_view:
    icon: mdi:battery-unknown
    view: yes
    entities:
      - group.device_batteries
      - group.tradfri_batteries

  device_batteries:
    name: Zwave Batteries
    entities:
      - sensor.zwave_pir_hallway
      - sensor.zwave_door_hallway

  tradfri_batteries:
    name: Trådfri Batteries
    entities:
      - sensor.ikea_remote_livingroom
      - sensor.ikea_remote_bedroom
      - sensor.ikea_remote_elin
      - sensor.ikea_remote_vilhelm

automation:
  - alias: Low Battery Sensors
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.zwave_pir_hallway
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.zwave_door_hallway
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.ikea_remote_livingroom
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.ikea_remote_bedroom
        above: 1
        below: 10
      - platform: numeric_state
        entity_id: sensor.ikea_remote_elin
        above: 1
        below: 10     
      - platform: numeric_state
        entity_id: sensor.ikea_remote_vilhelm
        above: 1
        below: 10
    action:
      - service: notify.pushbullet
        data_template:
          title: 'Battery low'
          message: >
            '{{ trigger.to_state.name }}'
