group: 
  floodsensors:
   view: yes
   name: Flood Sensors
   icon: mdi:water
   entities:
   - binary_sensor.sensor_12
   - binary_sensor.sensor_13

automation: 
- alias: Flooding in Kitchen 
  trigger:
    platform: state
    entity_id: binary_sensor.sensor_12
    to: 'on'
  action:
    - service: notify.pushbullet
      data:
        title: 'Kitchen Flood Sensor: '
        message: '*** WATER DETECTED BY KITCHEN SENSOR ***'
    - service: notify.slack
      data:
        title: 'Kitchen Flood Sensor: '
        message: '*** WATER DETECTED BY KITCHEN SENSOR ***'

- alias: Flooding in Bathroom
  trigger:
    platform: state
    entity_id: binary_sensor.sensor_13
    to: 'on'
  action:
    - service: notify.pushbullet
      data:
        title: 'Bathroom Flood Sensor: '
        message: '*** WATER DETECTED BY BATHROOM SENSOR ***'
    - service: notify.slack
      data:
        title: 'Bathroom Flood Sensor: '
        message: '*** WATER DETECTED BY BATHROOM SENSOR ***'

- alias: Refrigerator temperature high 
  trigger:
    platform: numeric_state
    entity_id: sensor.temerature_7 
    above: 12 
  action:
    - service: notify.pushbullet
      data:
        title: 'Refrigerator Temperature Sensor: '
        message: '*** REFRIGERATOR TEMPERATURE ABOVE 12 DEG C!!! ***'
    - service: notify.slack
      data:
        title: 'Refrigerator Temperature Sensor: '
        message: '*** REFRIGERATOR TEMPERATURE ABOVE 12 DEG C!!! ***'

- alias: Freezer temperature high
  trigger:
    platform: numeric_state
    entity_id: sensor.temperature_10
    above: -10
  action:
    - service: notify.pushbullet
      data:
        title: 'Freezer Temperature Sensor: '
        message: '*** FREEZER TEMPERATURE ABOVE -10 DEG C!!! ***'
    - service: notify.slack
      data:
        title: 'Freezer Temperature Sensor: '
        message: '*** FREEZER TEMPERATURE ABOVE -10 DEG C!!! ***'

