group: 
  floodsensors:
   view: yes
   name: Flood Sensors
   icon: mdi:water
   entities:
   - binary_sensor.sensor_12
   - binary_sensor.sensor_13

automation: 
- alias: Flooding in Kitchen 
  trigger:
    platform: state
    entity_id: binary_sensor.sensor_12
    to: 'on'
  action:
    - service: notify.pushbullet
      data:
        title: 'Kitchen Flood Sensor: '
        message: '*** WATER DETECTED ***'

- alias: Flooding in Bathroom
  trigger:
    platform: state
    entity_id: binary_sensor.sensor_13
    to: 'on'
  action:
    - service: notify.pushbullet
      data:
        title: 'Bathroom Flood Sensor: '
        message: '*** WATER DETECTED ***'
