automation: 

- alias: Smoke Sensor SMOKE
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgsd002_smoke_sensor_smoke
    to: '255'
  action:
    - service: notify.slack
      data:
        title: 'Fibaro Smoke Sensor: '
        message: '*** SMOKE DETECTED ***'


- alias: Smoke Sensor NOSMOKE
  trigger:
    platform: state
    entity_id: sensor.fibaro_system_fgsd002_smoke_sensor_smoke
    from: '255'
  action:
    - service: notify.slack
      data:
        title: 'Fibaro Smoke Sensor: '
        message: 'Smoke stopped -- Manually or automatically'


