homeassistant:
  customize:
    sensor.firewall: 
      icon: mdi:security
    sensor.ap: 
      icon: mdi:access-point
    sensor.switch:
      icon: mdi:switch
    sensor.office_switch: 
      icon: mdi:switch
    sensor.livingroom_switch:
      icon: mdi:switch
    sensor.gigaset_voip: 
      icon: mdi:phone-classic
    sensor.mini_app: 
      icon: mdi:server
    sensor.mini:
      icon: mdi:server
    sensor.ike:
      icon: mdi:server
    sensor.ip_camera:
      icon: mdi:webcam
    sensor.logitech_harmony:
      icon: mdi:remote


sensor:
  - platform: template
    sensors:
        firewall:
          friendly_name: 'Firewall'
          value_template: "{{ 'Online' if is_state('device_tracker.firewall', 'home') else 'Offline' }}"
        ap:
          friendly_name: 'Wifi Access point'
          value_template: "{{ 'Online' if is_state('device_tracker.ap', 'home') else 'Offline' }}"
        switch:
          friendly_name: 'Core Switch'
          value_template: "{{ 'Online' if is_state('device_tracker.switch', 'home') else 'Offline' }}"
        mini:
          friendly_name: 'mini - Hypervisor and NAS'
          value_template: "{{ 'Online' if is_state('device_tracker.minitillanderorg', 'home') else 'Offline' }}"
        mini_app:
          friendly_name: 'mini-app - Server VM'
          value_template: "{{ 'Online' if is_state('device_tracker.miniapptillanderorg', 'home') else 'Offline' }}"
        ike:
          friendly_name: 'ike - VPN Server VM'
          value_template: "{{ 'Online' if is_state('device_tracker.iketillanderorg', 'home') else 'Offline' }}"
        logitech_harmony:
          friendly_name: 'Harmony Hub'
          value_template: "{{ 'Online' if is_state('device_tracker.harmonyhub', 'home') else 'Offline' }}"
        ip_camera:
          friendly_name: 'IP Camera'
          value_template: "{{ 'Online' if is_state('device_tracker.34ce00d8b3e4', 'home') else 'Offline' }}"
        livingroom_switch:
          friendly_name: 'Livingroom Switch'
          value_template: "{{ 'Online' if is_state('device_tracker.living_room_switch__admin_ip', 'home') else 'Offline' }}"
        office_switch:
          friendly_name: 'Office Switch'
          value_template: "{{ 'Online' if is_state('device_tracker.office_switch__admin_ip', 'home') else 'Offline' }}"
        gigaset_voip:
          friendly_name: 'Gigaset VOIP gateway'
          value_template: "{{ 'Online' if is_state('device_tracker.siemens_gigaset_voip', 'home') else 'Offline' }}"


group:
  device_states:
    name: Device status
    entities:
    - sensor.firewall
    - sensor.ap 
    - sensor.switch
    - sensor.office_switch
    - sensor.livingroom_switch
    - sensor.mini
    - sensor.mini_app
    - sensor.ike
    - sensor.gigaset_voip
    - sensor.ip_camera
    - sensor.logitech_harmony

automation:
  - alias: 'Device Status'
    initial_state: 'on'
    trigger:
         - platform: state
           entity_id:
              - sensor.firewall
              - sensor.switch 
              - sensor.ap
              - sensor.mini
              - sensor.ike
              - sensor.mini_app
              - sensor.ip_camera
              - sensor.logitech_harmony
              - sensor.office_switch
              - sensor.livingroom_switch
              - sensor.gigaset_voip
           to: 'offline'
           for:
             minutes: 5
    action:
      - service: notify.pushbullet
        data_template:
          title: 'Device {{ trigger.to_state.name }} is'
          message: >
            '{{ trigger.to_state.state }}'
      - service: notify.slack
        data_template:
          title: 'Device {{ trigger.to_state.name }} is'
          message: >
            '{{ trigger.to_state.state }}'


